services:
  - type: web
    name: Titanos-leadgen
    env: node
    buildCommand: npm ci && npm run build && npx puppeteer browsers install chrome --path /opt/render/project/src/dist/puppeteer_cache
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/dist/puppeteer_cache
